name: Merge automatically created PR if it passed all checks

on:
  pull_request:
    types: [opened, synchronize]
  check_suite:
    types: [completed]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'automated pr')

    steps:
      - name: Find pr_number if needed
        id: pr-info
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "pr_number=${{ github.event.check_suite.pull_requests[0].number }}" >> $GITHUB_OUTPUT
            echo "sha=${{ github.event.check_suite.pull_requests[0].head.sha }}" >> $GITHUB_OUTPUT
          fi
      
      - name: Checkout and setup
        uses: actions/checkout@v4
      
      - name: Setup CLI
        run: |
          bash config/setup_cli.sh
      
      - name: Wait for checks
        uses: fountainhead/action-wait-for-check@v1.2.0
        id: wait-for-checks
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Build Documentation
          ref: ${{ steps.pr-info.outputs.sha || github.sha }}
      
      - name: Generate GitHub App Token
        uses: tibdex/github-app-token@v2
        id: generate-token
        with:
          app_id: ${{ secrets.GH_APP_ID }}
          private_key: ${{ secrets.GH_APP_PRIVATE_KEY }}
      
      - name: Automerge
        if: steps.wait-for-checks.outputs.conclusion == 'success'
        run: |
          gh pr merge ${{ steps.pr-info.outputs.pr_number }} \
            --merge \
            --auto \
            --delete-branch
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
